### ISSUE TITLE
android-sdk: Investigate multi-stage builds

### ISSUE THREAD

**Issue by osipxd** [RedMadRobot/android-docker-images#9]
It looks like [multi-stage](https://docs.docker.com/build/building/multi-stage/) builds may be useful to keep base, SDK and NDK build in one Dockerfile. But it is not clear for me if we can publish "intermediate" images or only the final? 

Here is an example of multi-stage builds usage: https://github.com/mingchen/docker-android-build-box/pull/124

**Comment by osipxd** [comment]
Problems:
1. There is no legal way to publish intermediate images, the corresponding issue is closed (https://github.com/moby/moby/issues/38197).
2. We can't publish multiple images with different tags in one `docker/build-push-action`, so we need multiple `build-push` actions with multiple `metadata` actions, and it looks like a huge rework of the CI pipeline. It also breaks reuse of `publish-image.yml` workflow.

Possible solutions:
 1. If we really need it, we can push intermediate images using [this ugly workaround](https://forums.docker.com/t/tag-intermediate-build-stages-multi-stage-build/34795/2)
 2. Heavily refactor CI workflows and use separated workflow for android SDK builds to not affect other images.
 3. Put everything in a single Dockerfile, but keep different workflows and build different targets in each workflow.

**Comment by master-bob** [comment]
Also do keep in mind that multi-stage builds benefit from reduced build times and more important for these sorts of projects smaller image sizes. Using a multi-stage Dockerfile brought the mingchen/docker-android-build-box size down from 16.2GB to 11.6GB, while adding more functionality, and reduced build time from ~18mins to ~10mins.

This project is much simpler, so I'm not sure how much benefit you'll get, but it would be possible to make this project's android-sdk:base multi-stage. For example one stage could be installing the necessary amd64 libraries, integrating the current amd64-*.sh into the Dockerfile.

**Comment by osipxd** [comment]
@master-bob, thank you, Your explanation confirms results of my small research.

> For example one stage could be installing the necessary amd64 libraries, integrating the current amd64-*.sh into the Dockerfile.

Yes, that would be a good case to use build stages. But I'm not sure if these libs are really needed for SDK or only for IDE. I didn't see these libs in your project and some of the other android builder images, so maybe I can just remove it. 
The only reason why I've added this script is [Android Studio installation guide](https://developer.android.com/studio/install#64bit-libs), but maybe it is just legacy and these libs are no more needed.

**Comment by master-bob** [comment]
I think the libs are necessary if you intend the project to be used with Android Studio.

**Comment by osipxd** [comment]
I've decided to use multi-stage builds to make it easier to locally build SDK and NDK images. Now it is possible to build these image with single command instead of "build base - build sdk - build ndk"
Link: #12
